### ISSUE TITLE
setup website

### ISSUE THREAD

**Issue by happypeter** [nervosbook/book#1]
refer to https://www.nervos.org/ for logo and color theme
reuse code of learning.nervos.org

**Comment by happypeter** [comment]
offer both Chinese and English version

**Comment by happypeter** [comment]
URL structure follow https://git-scm.com/book/zh/v2/%E8%B5%B7%E6%AD%A5-Git-%E5%9F%BA%E7%A1%80

**Comment by happypeter** [comment]
try to setup CI, ref: https://github.com/nervosnetwork/docs/blob/master/.circleci/config.yml

**Comment by happypeter** [comment]
deploy to https://github.com/nervosbook/nervosbook.github.io

**Comment by billie66** [comment]
apply for algolia docsearch

<img width="675" alt="Screen Shot 2019-05-28 at 6 01 02 PM" src="https://user-images.githubusercontent.com/102444/58469723-a1a96980-8172-11e9-94ed-fbd72c37c591.png">

**Comment by billie66** [comment]
https://circleci.com/docs/2.0/gh-bb-integration/#creating-a-github-user-key

**Comment by billie66** [comment]
I will apply for DocSearch again after the book is finished.

<img width="1527" alt="Screen Shot 2019-05-30 at 8 06 36 AM" src="https://user-images.githubusercontent.com/102444/58599319-539b7f80-82b2-11e9-8c0e-967731319639.png">

**Comment by happypeter** [comment]
cool

**Comment by billie66** [comment]
The circleci is working now,  so the code that pushed to GitHub every time will be automatically deployed to website
