### ISSUE TITLE
PDF generation

### ISSUE THREAD

**Issue by billie66** [nervosbook/book#11]
follow the method here

https://git-scm.com/book/en/v2

**Comment by billie66** [comment]
https://github.com/progit/progit2#how-to-generate-the-book

**Comment by billie66** [comment]
The progit text is written in  Asciidoc  format and need ruby environment to generate pdf book

**Comment by happypeter** [comment]
we don't use ruby, and we will stay in markdown format.

**Comment by billie66** [comment]
how to install prince
https://www.princexml.com/doc-install/#macos

**Comment by billie66** [comment]
how to install pandoc, download a tarball

https://github.com/jgm/pandoc/releases/tag/2.7.2

**Comment by happypeter** [comment]
cool now
