### ISSUE TITLE
I hope to provide MOBI document download.

### ISSUE THREAD

**Issue by li01452** [nervosbook/book#8]

**Comment by happypeter** [comment]
https://git-scm.com/book/en/v2 this book also provides mobi , so it's doable.

@billie66  plz investigate this

**Comment by billie66** [comment]
ok, i will do a research

**Comment by billie66** [comment]
https://medium.com/@blittler/creating-ebook-epub-and-mobi-files-from-markdown-fe1f2d6379a3

**Comment by billie66** [comment]
There are two steps to convert Markdown to MOBI:

firstly, convert Markdown to EPUB by Pandoc,

secondly, convert EPUB to MOBI by KindleGen

**Comment by billie66** [comment]
it's done

**Comment by happypeter** [comment]
good job
